# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'August_test_login' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for August_test_login

end
